### ISSUE TITLE
math_operation and shadow_removal modules not found

### ISSUE THREAD

**Issue by pawan9** [AuzanMuh/vehicle_detection#1]
File "_capture_init.py", line 7, in <module>
    import math_operation as mo
ImportError: No module named math_operation

File "_capture_init.py", line 10, in <module>
   import shadow_removal as sr
ImportError: No module named shadow_removal

I resolved other dependencies by installing them through `conda`.
where can i found these two modules ?

**Comment by auzanmuh** [comment]
sorry, i forgot to add module shadow removal and math_operation

**Comment by pawan9** [comment]
@AuzanMuh will u be adding them ?

**Comment by auzanmuh** [comment]
of course, I've done adding them. Sorry before.
